# Generated by Django 4.1.7 on 2023-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=70)),
                ('data', models.CharField(max_length=500)),
                ('time', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('is_liked', models.BooleanField(default=False)),
                ('image', models.CharField(default='http://surl.li/gxgxl', max_length=400)),
            ],
        ),
    ]
